package team316.navigation;

public enum ParticleType {
	OPPOSITE_ARCHON, OPPOSITE_GUARD, OPPOSITE_SOLDIER, OPPOSITE_VIPER, OPPOSITE_SCOUT, OPPOSITE_TURRET, ALLY_TURRET, ALLY_ARCHON, FIGHTING_ALLY, ALLY_DEFAULT, ZOMBIE, DEN, ARCHON_ATTACKED, PARTS, BIG_ZOMBIE, FAST_ZOMBIE, RANGED_ZOMBIE
}
